#!/bin/sh

#	checkout-and-build-mono
#	Check out mono from svn, apply our patches, and build and install mono.
#	Neil Mayhew - 2009-05-12

REVISION=152577
PROJECTS="libgdiplus mcs mono"
DIRECTORIES="libgdiplus mono"

[ -z "${MONO_PREFIX}" ] && MONO_PREFIX="/usr/local"

set -e

echo $0: Starting ...

if [ -e $0.config ]; then
	. $0.config

	if [ "$OLD_ARCH" != "$(uname -m)" ]; then
		echo $0: Switching architecture. Doing a 'make clean'
		for DIR in $DIRECTORIES
		do
			[ -d $DIR ] && (cd $DIR; make clean)
		done
	fi
fi

if [ -d .svn ]; then
	echo $0: Reverting and cleaning mono svn working copy ...
	svn revert -R .
	for dir in $PROJECTS
	do
		[ -e $dir ] && svn-clean $dir
	done
else
	echo $0: Creating mono svn working copy ...
	svn co --depth empty svn://anonsvn.mono-project.com/source/trunk .
fi

echo $0: Bringing mono svn working copy up to date ...
svn up -r$REVISION $PROJECTS

echo $0: Applying our patches ...
for PATCH in *.patch
do
	patch -t -N -p0 -i $PATCH
done

echo $0: Building mono ...
for DIR in $DIRECTORIES
do
	(cd $DIR; ./autogen.sh --prefix=$MONO_PREFIX; make)
done

echo OLD_ARCH=$(uname -m) > $0.config

echo $0: Installing mono ...
for DIR in $DIRECTORIES
do
	(cd $DIR; sudo make install)
done

# Some versions of nant expect mono to use the pkg-config name of 'mono', but 
# new versions of mono use name 'mono-2'. Support both until we upgrade or 
# fix our nant.
sudo ln -sf mono-2.pc $MONO_PREFIX/lib/pkgconfig/mono.pc

echo $0: Finished successfully.
